version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"


